#
# StickyChat
# Authors: SkyezerFox
#
# Main Configuration File
#

#
# DATABASE SETTINGS CAN BE IGNORED FOR THIS BUILD - they don't do anything uwu.
#
# Which storage method to use for data storage.
# Currently supports:
#   - H2
#   - PostgreSQL
#   - MySQL
#   - YAML
storage-method: postgresql

# Configure remote database settings.
# - You don't need to touch any of the settings here if you're using a local storage method!
data:
  database: minecraft
  tableprefix: stickychat_
  host: localhost
  port: 5432
  username: root
  password: password

# Configuration for chat.
chat:
  # The default format to use when creating a group.
  format: "&8%name%: %message%"

  # Disable join/quit messages - useful if you have a bungee plugin handling them for you already.
  disableJoinMessages: false
  disableQuitMessages: false

# Configuration options for SignSpy
# This feature is WIP!
sign-spy:
  enabled: false

#
# Language Configuration
#
# Use these configs to configure the feel of StickyChat~
# Todo: Move these into a separate language.yml file.
language:
  prefix: "&6StickyChat &r&8» &r"

  sign-spy:
    sign-created: "&aPlayer '%name%' (%uuid%) placed a sign at %x%, %y%, %z% with content: '%content%'"
