name: StickyChat
authors: [SkyezerFox]
version: 3.0.0
main: com.dumbdogdiner.stickychat.bukkit.StickyChatPlugin
commands:
#  mail:
#    description: Send a mail to another player on the network.
#    usage: /mail [filter/player] [player] [unread]
  message:
    description: Send a private message to a player currently online.
    usage: /message [player] <message>
    aliases: ["msg", "tell", "whisper"]
  reply:
    description: Reply to the last private message you received.
    usage: /reply <message>
    aliases: ["r"]
#  stickychat:
#    description: StickyChat management and configuration.
#    usage: /stickychat [reload]
#    aliases: ["chat"]
#  nickname:
#    description: Set your nickname, or another player's.
#    usage: /nickname <name|player> [name]
#    aliases: ["nick"]
#  staffchat:
#    description: Enable or disable staff chat.
#    usage: /staffchat
#    aliases: ["sc"]
api-version: "1.16"
