# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Bukkit plugin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-bukkit-plugin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build project
        run: chmod +x gradlew && ./gradlew build

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v2
        with:
          name: StickyChat
          path: bukkit/build/libs/StickyChat-*.jar
